/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReasonToDeleteTicket.java
 *
 * Created on 11/08/2011, 01:52:52 PM
 */
package com.openbravo.pos.sales;

import com.openbravo.pos.forms.AppLocal;

/**
 * clase for Selection of reason for refund, cancellation or cancellation of order sent to comanada
 * @author Carlos Prieto - SmartJSP S.A.S.
 */
public class ReasonToDeleteTicket extends javax.swing.JPanel {

    /** Creates new form ReasonToDeleteTicket */
    public ReasonToDeleteTicket(String label1, String label2) {
        initComponents();
        initLabels();
//        jLabel1.setText(label1);
//        jLabel2.setText(label2); 
    }
    
    /**
     * set items to display for the selection of reasons
     * @param reason 
     */
    public void setReason(String reason){
        String[] reasonList = reason.split(",");
        for(int i =0; i < reasonList.length; i++)
        jComboBox1.addItem(reasonList[i]);
    }

    /**
     * returns the selected reason
     * @return 
     */
    public String getReason(){
        return (String) jComboBox1.getSelectedItem();
    }
    
    /**
     * returns if affects  inventory
     * @return 
     */
    public boolean afectsStock(){
        if(jRadioButton1.isSelected())
            return true;
        else
            return false;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Razon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 88, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Afecta el inventario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 12, 0, 0);
        add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 18, 0, 79);
        add(jComboBox1, gridBagConstraints);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 97;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 79);
        add(jRadioButton1, gridBagConstraints);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 19, 79);
        add(jRadioButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

    private void initLabels() {
        jLabel2.setText(AppLocal.getIntString("label.reasontodeleteticket.doesaffectinventory"));
        jLabel1.setText(AppLocal.getIntString("label.reasontodeleteticket.reason"));
        jRadioButton1.setText(AppLocal.getIntString("label.reasontodeleteticket.yes"));
        jRadioButton2.setText(AppLocal.getIntString("label.reasontodeleteticket.no"));
    }
}
